### ISSUE TITLE
priceR::convert_currencies date issue

### ISSUE THREAD

**Issue by antoine4ucsd** [stevecondylios/priceR#51] opened 2023-10-20 06:46 UTC
Hello
I cannot return converted currenvy (was working with former version of priceR. I have installed the latest 1.0
```
> priceR::convert_currencies(235,"USD","AED",date = Sys.Date())
Error in `dplyr::semi_join()`:
! Can't join `x$date` with `y$date` due to incompatible types.
`x$date` is a <character>.
 `y$date` is a <date>.
Run `rlang::last_trace()` to see where the error occurred.
```
thank you!

**Comment by stevecondylios** [comment] 2023-10-20 23:10
This for reporting this. It's a duplicate of https://github.com/stevecondylios/priceR/issues/49 which has been fixed in the GitHub version of priceR but isn't on CRAN just yet. 

Please install priceR with 

```r
devtools::install_github("stevecondylios/priceR")
```

close and reopen RStudio, and `convert_currencies()` should work as expected.

**Closed by stevecondylios** 2023-10-20 23:10 UTC

**Comment by antoine4ucsd** [comment] 2023-10-21 05:08
thank you
